import type { Engagement, Finding } from "@prisma/client";
import { execSummaryMarkdown } from "@/lib/ai-report";

export type EngagementWithFindings = Engagement & { findings: Finding[] };

export const SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"] as const;

export function severityRank(s: string): number {
  const i = (SEVERITY_ORDER as readonly string[]).indexOf(s);
  return i === -1 ? SEVERITY_ORDER.length : i;
}

/** Findings sorted most-severe first. */
export function sortFindings(findings: Finding[]): Finding[] {
  return [...findings].sort((a, b) => severityRank(a.severity) - severityRank(b.severity));
}

/** Count of findings per severity (only non-zero buckets, severe first). */
export function severityCounts(findings: Finding[]): { severity: string; count: number }[] {
  return SEVERITY_ORDER.map((sev) => ({
    severity: sev,
    count: findings.filter((f) => f.severity === sev).length,
  })).filter((b) => b.count > 0);
}

function fmtDate(d: Date): string {
  return new Date(d).toISOString().slice(0, 10);
}

/** Render an engagement and its findings as a client-ready Markdown report. */
export function buildMarkdown(e: EngagementWithFindings): string {
  const lines: string[] = [];

  lines.push(`# Security Assessment Report — ${e.name}`);
  lines.push("");
  lines.push(`- **Client:** ${e.client || "—"}`);
  lines.push(`- **Type:** ${e.type}`);
  lines.push(`- **Status:** ${e.status}`);
  lines.push(`- **Date:** ${fmtDate(e.createdAt)}`);
  lines.push(
    `- **Authorization:** ${
      e.authorized
        ? `Authorized${e.authorizedBy ? ` by ${e.authorizedBy}` : ""}`
        : "NOT AUTHORIZED"
    }`,
  );
  lines.push("");

  // AI-drafted executive summary (deterministic synthesis from findings).
  lines.push(execSummaryMarkdown(e));

  const counts = severityCounts(e.findings);
  if (counts.length) {
    lines.push("| Severity | Count |");
    lines.push("| --- | --- |");
    for (const c of counts) lines.push(`| ${c.severity} | ${c.count} |`);
    lines.push("");
  }

  if (e.scope) {
    lines.push("## Scope");
    lines.push("");
    lines.push(e.scope);
    lines.push("");
  }

  lines.push("## Findings");
  lines.push("");
  const sorted = sortFindings(e.findings);
  if (sorted.length === 0) {
    lines.push("_No findings recorded._");
  } else {
    sorted.forEach((f, i) => {
      lines.push(`### ${i + 1}. ${f.title}`);
      lines.push("");
      lines.push(`- **Severity:** ${f.severity}`);
      lines.push(`- **Status:** ${f.status.replace(/_/g, " ")}`);
      lines.push("");
      if (f.description) {
        lines.push("**Description**");
        lines.push("");
        lines.push(f.description);
        lines.push("");
      }
      if (f.recommendation) {
        lines.push("**Recommendation**");
        lines.push("");
        lines.push(f.recommendation);
        lines.push("");
      }
    });
  }

  lines.push("---");
  lines.push(
    "_Generated by RD-AISEC. For authorized security testing and education only._",
  );
  return lines.join("\n");
}

/** Filesystem-safe slug for the download filename. */
export function reportFilename(e: Engagement): string {
  const slug = e.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return `report-${slug || e.id}.md`;
}
